server:
  port: 9080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: prod
  liquibase:
    change-log: classpath:db.changelog/db.changelog-prod.yml
---
spring:
  config:
    activate:
      on-profile: dev
  liquibase:
    change-log: classpath:db.changelog/db.changelog-dev.yml

logging:
  level:
    liquibase: DEBUG
    liquibase.executor.jdbc.JdbcExecutor: DEBUG
